### ISSUE TITLE
Convert the logo to svg

### ISSUE THREAD

**Issue by Khalid-212** [Khalid-212/RACKWATCH#2]

**Comment by Prithwi32** [comment]
hey. I would like to solve this issue.
please assign me.

**Comment by Khalid-212** [comment]
sure @Prithwi32 go ahead I'm assigning you

**Comment by Prithwi32** [comment]
please may I know all logos which are in Png format must be replaced or only one logo which is in frontend>src>assets>logo.png ?

**Comment by Khalid-212** [comment]
yes, that is the logo and if you can adjust the sizes of the logos in the code. after converting it to svg

**Comment by Prithwi32** [comment]
thank you I will try my best.
