### ISSUE TITLE
update the server to use the json file

### ISSUE THREAD

**Issue by Khalid-212** [Khalid-212/RACKWATCH#3]

**Comment by Divi03** [comment]
<img width="300" alt="image" src="https://github.com/Khalid-212/RACKWATCH/assets/92048020/28d7024f-f445-4e41-b6f8-812ddbd9a131">
<img width="382" alt="image" src="https://github.com/Khalid-212/RACKWATCH/assets/92048020/15bed6ef-d773-487a-90fd-2d032b9df06f">
<br>
<br>
I updated the /records route 
if it resolves the issue should I push it

**Comment by Khalid-212** [comment]
@Divi03 if it is working for you, sure make a pr and i'll check it
